### PR TITLE
Fixed vagrant/bootstrap.sh & Added my name

### PR DESCRIPTION
**Pull request by K0HAX**

### CODE REVIEW

**Comment by K0HAX** [comment]
I've also fixed a bug in bootstrap.sh.

```
==> default: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: The following extra packages will be installed:
==> default:   apache2-bin apache2-data libapr1 libaprutil1 libaprutil1-dbd-sqlite3
==> default:   libaprutil1-ldap ssl-cert
==> default: Suggested packages:
==> default:   apache2-doc apache2-suexec-pristine apache2-suexec-custom apache2-utils
==> default:   openssl-blacklist
==> default: The following NEW packages will be installed:
==> default:   apache2 apache2-bin apache2-data libapr1 libaprutil1 libaprutil1-dbd-sqlite3
==> default:   libaprutil1-ldap ssl-cert
==> default: 0 upgraded, 8 newly installed, 0 to remove and 0 not upgraded.
==> default: Need to get 1,272 kB of archives.
==> default: After this operation, 5,057 kB of additional disk space will be used.
==> default: Get:1 http://archive.ubuntu.com/ubuntu/ trusty/main libapr1 i386 1.5.0-1 [88.8 kB]
==> default: Get:2 http://archive.ubuntu.com/ubuntu/ trusty/main libaprutil1 i386 1.5.3-1 [76.6 kB]
==> default: Get:3 http://archive.ubuntu.com/ubuntu/ trusty/main libaprutil1-dbd-sqlite3 i386 1.5.3-1 [10.3 kB]
==> default: Get:4 http://archive.ubuntu.com/ubuntu/ trusty/main libaprutil1-ldap i386 1.5.3-1 [8,552 B]
==> default: Err http://archive.ubuntu.com/ubuntu/ trusty-updates/main apache2-bin i386 2.4.7-1ubuntu4.13
==> default:   404  Not Found [IP: 91.189.88.162 80]
==> default: Err http://security.ubuntu.com/ubuntu/ trusty-security/main apache2-bin i386 2.4.7-1ubuntu4.13
==> default:   404  Not Found [IP: 91.189.91.26 80]
==> default: Err http://security.ubuntu.com/ubuntu/ trusty-security/main apache2-data all 2.4.7-1ubuntu4.13
==> default:   404  Not Found [IP: 91.189.91.26 80]
==> default: Err http://archive.ubuntu.com/ubuntu/ trusty-updates/main apache2 i386 2.4.7-1ubuntu4.13
==> default:   404  Not Found [IP: 91.189.88.162 80]
==> default: Err http://security.ubuntu.com/ubuntu/ trusty-security/main apache2 i386 2.4.7-1ubuntu4.13
==> default:   404  Not Found [IP: 91.189.91.26 80]
==> default: Get:5 http://archive.ubuntu.com/ubuntu/ trusty/main ssl-cert all 1.0.33 [16.6 kB]
==> default: Fetched 201 kB in 2s (71.7 kB/s)
==> default: E
==> default: : 
==> default: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/a/apache2/apache2-bin_2.4.7-1ubuntu4.13_i386.deb  404  Not Found [IP: 91.189.91.26 80]
==> default: E
==> default: : 
==> default: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/a/apache2/apache2-data_2.4.7-1ubuntu4.13_all.deb  404  Not Found [IP: 91.189.91.26 80]
==> default: E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/a/apache2/apache2_2.4.7-1ubuntu4.13_i386.deb  404  Not Found [IP: 91.189.91.26 80]
==> default: 
==> default: E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

apt-get update needs to be run before apt-get install, because the box's apt cache is out of date.

**Review by tfitch — APPROVED** [review]
:shipit:

**Comment by purplefeetguy** [comment]
you do pull requests for everything eh?


Purplefeetguy (AKA Jose de Jesus Castillo)
Wannabe Programmer

"Most programming languages are partly a way of expressing things in terms of other things and partly a basic set of given things."
PJ Landin


________________________________

**Comment by K0HAX** [comment]
Sure, when I can. 😄

**Pull request merged**
